apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      nodePort: 30080
      port: 80
      targetPort: 80
  type: NodePort
