apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: multitool-http
      port: 9002
      targetPort: 8080