apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    service.beta.kubernetes.io/yandex-load-balancer-type: "external"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
