{
 "title": "Node monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "stat",
   "description": "The average CPU usage percentage per instance over the last 1 minute",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"node_exporter\"}",
     "legendFormat": "1-min load"
    },
    {
     "expr": "node_load5{job=\"node_exporter\"}",
     "legendFormat": "5-min load"
    },
    {
     "expr": "node_load15{job=\"node_exporter\"}",
     "legendFormat": "15-min load"
    }
   ]
  },
  {
   "title": "Filesystem size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"\", mountpoint=\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_free_bytes{fstype!=\"\", mountpoint=\"/\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}