---
all:
  hosts:
    clickhouse-01:
      ansible_host: "158.160.165.114"
    vector-01:
      ansible_host: "130.193.35.244"
    lighthouse-01:
      ansible_host: "84.201.170.36"
  children:
    clickhouse:
      children:
        clickhouse_prod:
          hosts:
            clickhouse-01:
    vector:
      children:
        vector_prod:
          hosts:
            vector-01:
    lighthouse:
      children:
        lighthouse_prod:
          hosts:
            lighthouse-01:
  vars:
    ansible_user: user