apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx + Multitool App</title>
    </head>
    <body>
      <h1>Welcome to Nginx + Multitool App</h1>
    </body>
    </html>