apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Моя страница</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                margin-top: 50px;
                background-color: #f0f8ff;
            }
            h1 {
                color: #2c3e50;
            }
        </style>
    </head>
    <body>
        <h1>Добро пожаловать в Nginx!</h1>
    </body>
    </html>